include "#!./gradlew --console=plain --quiet :frontend:printConveyorConfig"

conveyor.compatibility-level = 22

app {
  display-name = Kassette
  fsname = kassette
  rdns-name = com.cyanotic.kassette
  vendor = Cyanotic
  description = "A small, focused NES emulator for desktop and the browser."
  license = MIT
  vcs-url = "https://github.com/Otacon/Kassette"

  machines = [
    windows.amd64,
    linux.amd64.glibc,
    mac.amd64,
    mac.aarch64
  ]

  icons = "frontend/src/wasmJsMain/resources/icons/icon-512.png"
  updates = background

  jvm.system-properties."org.lwjgl.util.NoHashChecks" = true

  site {
    base-url = "https://github.com/Otacon/Kassette/releases/latest/download"
    copy-to = "github:Otacon/Kassette"
  }
}
