package nes2.cpu

enum class Operation(val pageCrossingPenalty: Boolean) {
    ADC(pageCrossingPenalty = true),
    AND(pageCrossingPenalty = true),
    ORA(pageCrossingPenalty = true),
    EOR(pageCrossingPenalty = true),
    LDA(pageCrossingPenalty = true),
    CMP(pageCrossingPenalty = true),
    SBC(pageCrossingPenalty = true),
    LDX(pageCrossingPenalty = true),
    LDY(pageCrossingPenalty = true),

    STA(pageCrossingPenalty = false),
    STX(pageCrossingPenalty = false),
    STY(pageCrossingPenalty = false),
    TAX(pageCrossingPenalty = false),
    TAY(pageCrossingPenalty = false),
    TXA(pageCrossingPenalty = false),
    TYA(pageCrossingPenalty = false),
    TSX(pageCrossingPenalty = false),
    TXS(pageCrossingPenalty = false),
    INX(pageCrossingPenalty = false),
    INY(pageCrossingPenalty = false),
    DEX(pageCrossingPenalty = false),
    DEY(pageCrossingPenalty = false),
    CPX(pageCrossingPenalty = false),
    CPY(pageCrossingPenalty = false),
    BIT(pageCrossingPenalty = false),
    CLC(pageCrossingPenalty = false),
    SEC(pageCrossingPenalty = false),
    CLI(pageCrossingPenalty = false),
    SEI(pageCrossingPenalty = false),
    CLV(pageCrossingPenalty = false),
    CLD(pageCrossingPenalty = false),
    SED(pageCrossingPenalty = false),
    INC(pageCrossingPenalty = false),
    DEC(pageCrossingPenalty = false),
    ASL(pageCrossingPenalty = false),
    LSR(pageCrossingPenalty = false),
    ROL(pageCrossingPenalty = false),
    ROR(pageCrossingPenalty = false),
    BCC(pageCrossingPenalty = false),
    BCS(pageCrossingPenalty = false),
    BEQ(pageCrossingPenalty = false),
    BNE(pageCrossingPenalty = false),
    BMI(pageCrossingPenalty = false),
    BPL(pageCrossingPenalty = false),
    BVC(pageCrossingPenalty = false),
    BVS(pageCrossingPenalty = false),
    JMP(pageCrossingPenalty = false),
    JSR(pageCrossingPenalty = false),
    RTS(pageCrossingPenalty = false),
    PHA(pageCrossingPenalty = false),
    PLA(pageCrossingPenalty = false),
    PHP(pageCrossingPenalty = false),
    PLP(pageCrossingPenalty = false),
}